name: Initialise the app environment

inputs:
  node-version:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '${{ inputs.node-version }}'

    - name: Install dependencies
      shell: bash # ! the dev has to specify this line at every `run` step in a composite action
      run: npm install   
